javascript.md
- Removed redundant examples
- Explicitly show good and bad examples where relevant
This does not add, remove or change any of the rules.
=> Updates the JavaScript styleguide with better examples.

javascript.md
* Adds some additional information differentiating `let` from `const`
per MDN docs.
=> Updates the Variables section.

engineering/elixir.md
=> Add two line `do:` preference

engineering/javascript.md
Renames "Variables" section to "Assignment."
=> Adds destructuring within Assignment section.

engineering/ember.md
Not sure if there is already a consensus about where they go,
but this is where I think they should go.
=> Ember: Add lifecycle hooks to organizing modules

engineering/ember.md
* We'll continue to use modules for Ember Data though
=> Prefer destructuring Ember instead of using shims

engineering/ember.md
=> [Ember] Always use `action` to pass actions

engineering/ember.md
=> [Ember] Don't yield `this`

engineering/ember.md
=> Ember templates: add note about ordering attrs and actions within HTML

engineering/javascript.md
=> Do not use spaces inside array brackets

engineering/ember.md
* We have this same info up in the `Models` section
=> Remove repeated info on model organization

.github/CODE_OF_CONDUCT.md, .github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, .github/README_TEMPLATE.md
=> Github open source project template

ux-dev/html.md
Added some additional reading, any other suggestions are welcome
=> Update the HTML doc with modern reading and small fixes

ux-dev/css.md
Update Declaration Order with descriptive comments that better outline why CSS properties are in the order they are in.
=> Fixes #122 - Update Declaration Order with better descriptive comments

engineering/ember.md
Update our ember-data imports to reflect the new ED modules.
=> use ember-data modules

README.md, ux-dev/pixel-perfection.md
=> Closes #137 UXD: New pixel-perfection.md

ux-dev/ux-developer-onboarding.md
* Remove blog/team page reference
* Add editors and tools suggestions
* Reorganize questions section
* Add git workflow from wiki
* Reorganize the research and questions section
=> Fixes #134 - update Onboarding document

ux-dev/beginning-a-project.md
Closes [133](https://github.com/DockYard/styleguides/issues/133)
=> Closes #133 UXD - Update beginning a project

ux-dev/html.md
Closes #130.
* Adds attribute order section
* Updates section on white space/line breaks
* Expands upon comments section
* Additions to common patterns, QA, and renamed resources section
=> #130: updates html styleguide

ux-dev/stylelint-config-narwin.md
=> Add stylelint-config-narwin property order docs

engineering/handlebars.md
Closes #155 Update handlebars.md to match whitespace/formatting recommendations in html.md
=> Closes #155 Closes #155 Update handlebars.md to match whitespace/formatting recommendations in html.md

engineering/ruby.md
Various updates to the Ruby Style Guide by Dan B. & Lucas C.
=> Updates to Ruby Style Guide

ux-dev/accessibility-a11y.md
**Changes proposed in this pull request**
* Adds information on keyboard and screenreader testing
* Adds helpful tips section
* Adds animation details
=> Update UXD accessibility guide

README.md, ux-dev/accessibility-a11y.md
- Add semantic markup section
- Add `lang` attribute section
- Add ARIA use section
- Add landmark regions section
- Add heights section
- Add units section
- Format keyboard shortcuts
=> Update accessibility guide with markup and styling tips

README.md, ux-dev/codepen.md
Adding a page for the Codepen Best Practices from today's UXD
=> Add Codepen Styleguide

ux-dev/beginning-a-project.md, ux-dev/class-naming-conventions.md, ux-dev/css.md
Change `https` to `http` in SMACSS urls
=> Update SMACSS urls to remove 's'

README.md, ux-dev/accessibility-a11y.md, ux-dev/pull-requests.md
- Add page about PR writing and reviewing
- Add link for it to the readme
- Add link in a11y doc for how to enable keyboard tabbing in FF for Mac
=> add page for PR writing and reviewing

README.md, ux-dev/team-values.md
This PR adds UXD team values, explaining how we put DockYard's core values into practice.
=> Add UXD team values

general/git.md
This is not intended to be the full encompassing guide on Git, and only
a basic guide. I'd like to provide basic suggestions to the team, in order
to make our commits more consistent. Project teams and individuals can use
this as a guide, and are free to make modifications as they see fit.
Signed-off-by: Doug Yun <doug.yun@dockyard.com>
=> Start basic Git styleguide

README.md
=> Update README: Add General section and Git guide
